version: "3.9"

services:
  buttplug-rs-ffi-wasm-demo:
    image: nginx:alpine
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "3003:8080"
    volumes:
      - ./container/nginx:/etc/nginx
      - ./static:/var/www/public/html
    restart: always
